import '../styles/globals.css';
import Head from 'next/head';
import Image from 'next/image';
import PeopleGrid from '../components/PeopleGrid/PeopleGrid';
import styles from '../styles/Home.module.css';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://fonts.googleapis.com/css2?family=Archivo+Black&display=swap'
          rel='stylesheet'
        />
        <link rel='icon' type='image/svg+xml' href='./brand/logo.svg' />
        <link
          href='https://fonts.googleapis.com/css2?family=Michroma&display=swap'
          rel='stylesheet'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap'
          rel='stylesheet'
        />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
